name: Format_Check
run-name: Format_Check
on:
  pull_request:
    branches:
      - master
jobs:
  Format_Check:
    runs-on: ubuntu-latest
    steps:
      - name: Format Check
        uses: actions/checkout@v4
      - run: |
          cd ${{ github.workspace }} 
          make check_format
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/checkout@v4
      - run: |
          cd ${{ github.workspace }} 
          make test
